### ISSUE TITLE
Dockerize flask webapp

### ISSUE THREAD

**Issue by einarpersson** [tullinge/booking#12]
The web application should be built and deployed as an docker image, and optimized for concurrency.

We should create a Dockerfile and use a suitable base image. Maybe [tiangolo/uwsgi-nginx-flask](https://www.digitalocean.com/community/tutorials/how-to-build-and-deploy-a-flask-application-using-docker-on-ubuntu-18-04) or [tiangolo/meinheld-gunicorn-flask](https://github.com/tiangolo/meinheld-gunicorn-flask-docker)

**Comment by vilhelmprytz** [comment]
I have looked at `meinheld-gunicorn-flask-docker`. Seems like it assumes the Flask project itself lives under a sub directory (opposite to our setup)?

**Comment by einarpersson** [comment]
Ah, I missed that you were working on this. I've done some experiments myself, will do a PR shortly that you can have a look at

**Comment by vilhelmprytz** [comment]
No worries, I hadn't done much research into this yet :smile:
