### ISSUE TITLE
Add Travis integration

### ISSUE THREAD

**Issue by vilhelmprytz** [tullinge/booking#16]
A Travis CI configuration had already been committed.

**Comment by vilhelmprytz** [comment]
I believe @einarpersson has the permissions to add this integration to the GitHub project. The configuration file, `.travis.yml` with some basic testing is already added to the project. It currently validates code style using `flake8` and `black`. There is room for some basic unit testing as well, but considering the size of this project, unit testing might be overdoing it a bit.

**Comment by einarpersson** [comment]
I'm on it! @VilhelmPrytz

**Comment by einarpersson** [comment]
![image](https://user-images.githubusercontent.com/6043691/70621966-22b1e500-1c1b-11ea-89c8-3262bb078620.png)

![image](https://user-images.githubusercontent.com/6043691/70621998-378e7880-1c1b-11ea-8f0c-50c0d60b02ff.png)


:tada:

**Comment by vilhelmprytz** [comment]
Hmm, so we're using the "pro" variant, [travis-ci.com](travis-ci.com) and not [travis-ci.org](travis-ci.org)?

**Comment by einarpersson** [comment]
I believe [travis-ci.com](https://travis-ci.com) is the way to go for all projects since last year (they are merging).

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
