### ISSUE TITLE
Ta bort känsliga uppgifter

### ISSUE THREAD

**Issue by einarpersson** [tullinge/booking#2]
Känsliga uppgifter t.ex. användarnamn och lösenord till databaser bör inte versionshanteras.

Ha dom lokalt på era datorer (och lägg till t.ex. `credentials.txt` till `.gitignore`) eller på annat ställe.

https://security.stackexchange.com/questions/191590/why-is-storing-passwords-in-version-control-a-bad-idea

PS. Efter att ni tagit bort dem från `README.md` bör ni byta lösenord också helst, eftersom historik sparas i git (det är ju det som är poängen liksom...)

Okay? =)

**Comment by fredrikberzins** [comment]
fixat

**Comment by einarpersson** [comment]
I https://github.com/tullinge/booking/blob/master/student/student.py ligger det fortfarande hemligheter.

Mitt förslag för att lösa situationen nu:
- Skapa en ny fil som heter typ `config.py`
- Fyll `config.py` med all nödvändig info om databasen
- Lägg till `config.py` till `.gitignore` så att den **inte** hamnar uppe på Github
- **Byt lösenord** på databasen, eftersom det nuvarande lösenordet ska betraktas som "läckt". Använd en lösenordgenerator så att det blir långt och svårt.
- Dela lösenordet med varandra och med mig på ett annat sätt (Post-it, Vklass, ...)

**Comment by fredrikberzins** [comment]
fixat
