### ISSUE TITLE
Feedback from testers

### ISSUE THREAD

**Issue by fredrikberzins** [tullinge/booking#35]
- Feedback
    - Students should see witch other people student have chosen the activity before choosing.
    - All questions should not have to be obligatory. (Mostly for extra/other questions)
    - Not working on all phones. (Buttons glitching together)
    - No CSS padding on buttons.
    - High light the button to choose an activity. (a lot of people missed it)

**Comment by vilhelmprytz** [comment]
- **Students should see witch other people student have chosen the activity before choosing.**
    - I reckon students should not have the ability to access this information.
- **All questions should not have to be obligatory. (Mostly for extra/other questions)**
    - Definitely a good point, open separate issue! (might not have the time to finish for the initial release though)
- **Not working on all phones. (Buttons glitching together)**
    - I've tried on a few different devices without any problems. Which button is this referring to? Please open a separate issue with more information.
- **No CSS padding on buttons.**
    - Yes, intentionally skipped this to be able to focus on higher priority stuff. Open a separate issue.
- **Highlight the button to choose an activity. (a lot of people missed it)**
    - Another good point, maybe increase the size? Open a separate issue.

**Comment by vilhelmprytz** [comment]
#37 and #38 covers parts of this feedback. @02TheBear can you open issues for the remaining ones (and then close this issue)?
