### ISSUE TITLE
Lägg till user stories i Readme:n

### ISSUE THREAD

**Issue by einarpersson** [tullinge/booking#4]
Lägg upp en lista på _user stories_ i `README.md` och bocka av dessa successivt. 
## User stories
- [x] Som en _elev_ kan jag se en lista på alla tillgängliga aktiviteter
- [x] Som en _elev_ kan jag läsa mer detaljer om en aktivitet
- [ ] ...
- [x] Som en _administratör_ kan jag ...

**PS.**
Vad är en user story? Läs [denna](https://www.mountaingoatsoftware.com/agile/user-stories)

**Comment by einarpersson** [comment]
Hej! Är det något ni undrar eller som är oklart vad gäller denna? Har ni läst länken?

Vi behöver ha en gemensam bild av vad som förväntas och var vi står just nu.

**Comment by fredrikberzins** [comment]
alt till lagt
