### ISSUE TITLE
Jockes feedback

### ISSUE THREAD

**Issue by fredrikberzins** [tullinge/booking#41]
- 404 page not found on admin/classes/{class id}/studens.
- 500 internal server error when making a class that already exists
- edit the number of spaces on an activity.
    - (edit all activity info.)
-  print out student list on admin/student (button)
    - get all codes in amounts of a class
- codes
    - individual codes (individual codes sent by email)
    - Mentor login so they see 
    - CSV import all students separately

**Comment by vilhelmprytz** [comment]
- **404 page not found on admin/classes/{class id}/studens.**
    - This was fixed in 5abe3a5b8d9672c48a08169210eef190dff2c7f5 already
- **500 internal server error make a duplicate class.**
    - When creating a class that already existed?
- **edit the number of spaces on an activity.**
    - Open a separate issue, all values should be modifiable
-  **print out student list on admin/student**
    - I'm not sure I understand this one?
- **codes**
    - **individual codes (individual codes sent by email)**
        - Sending by email would require **a lot** of extra work. Also, someone would at some point have to type in all the email addresses of users? Do we really want to do that?
    - **Mentor login so they see**
        - Admin user with restricted privileges?
    - **CSV import all students separately**
        - The system was designed to work without someone having to either manually entering student data or importing from a file. Importing from a file would be doable, but also destroys the purpose of anonymized codes.

**Comment by fredrikberzins** [comment]
made separate issues
